# Generated by Django 4.1.7 on 2023-02-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_product_alter_customer_user_shippingaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='../static/images/default.png', null=True, upload_to='product'),
        ),
    ]
